spool logs/ods_gate_dblink.log

DROP DATABASE LINK "OATI_GATE.FORS.RU"
/
CREATE DATABASE LINK "OATI_GATE.FORS.RU" CONNECT TO OATI_GATE
 IDENTIFIED BY oati_gate
 USING '(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = 172.16.132.74)(PORT = 1521))(CONNECT_DATA =(SERVER = DEDICATED)(SERVICE_NAME = test)))'
/
spool off
exit
